name: run-tests

on: [ push ]

jobs:
  tests:
    name: P${{ matrix.php }}
    runs-on: ubuntu-latest

    env:
      APP_ENV: "testing"

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1 ]

    services:
      mysql:
        image: mariadb:10
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: default
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    #      redis:
    #        image: redis
    #        ports:
    #          - 6379/tcp
    #        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare .env.testing file
        run: php -r "file_exists('.env.testing.github') && copy('.env.testing.github', '.env.testing');"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v2
          coverage: xdebug

      - name: Setup Memcached
        uses: niden/actions-memcached@v7

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress

      - name: Setup Laravel Passport
        run: |
          php artisan passport:install --env=testing
        env:
          DB_CONNECTION: mysql
          DB_USERNAME: root
          DB_DATABASE: default

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
        env:
          DB_CONNECTION: mysql
          DB_USERNAME: root
          DB_DATABASE: default

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/logs/clover.xml
